version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "debian"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
