server:
  port: 8888
spring:
  application:
    name: spring-config
  cloud:
    config:
      server:
        git:
          uri: http://localhost:10080/test/cloud-config.git
          searchPaths: '{application}/{profile},global/{profile}'